name = "oaktree-backend"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = [ "nodejs_compat" ]

[browser]
binding = "BROWSER"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "moltbot-db"
database_id = "97634677-4bac-44d1-bd02-6c733328a137"

[[send_email]]
name = "EMAIL"
destination_address = "rattajak.n@gmail.com"

[triggers]
crons = ["0 * * * *"] # Every hour

