import { Env } from './index';

export async function sendDailyEmailReport(env: Env) {
  console.log("Preparing daily email report...");

  // 1. Fetch latest reports (for today)
  const { results } = await env.DB.prepare(
    'SELECT * FROM daily_reports WHERE report_date = DATE("now")'
  ).all();
  const reports = (results || []) as any[];

  if (reports.length === 0) {
    console.log("No reports generated today. Skipping email.");
    return;
  }

  // 2. Construct Email Content
  let emailHtml = `
    <div style="font-family: 'Georgia', serif; max-width: 600px; margin: 0 auto; color: #333; line-height: 1.6;">
      <h1 style="color: #27ae60; border-bottom: 2px solid #27ae60; padding-bottom: 10px;">Oaktree Agent: Daily Intelligence</h1>
      <p style="font-style: italic; color: #666;">"The most important thing is the most important thing." - A Howard Marks inspired briefing.</p>
      <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
  `;

  for (const report of reports) {
    const takeaways = JSON.parse(report.key_takeaways || '[]');
    const sentiment = report.sentiment_score > 0.3 ? 'Bullish' : report.sentiment_score < -0.3 ? 'Bearish' : 'Neutral';

    emailHtml += `
      <div style="margin-bottom: 40px;">
        <h2 style="margin: 0; color: #000;">${report.symbol} <span style="font-size: 14px; font-weight: normal; color: ${report.sentiment_score > 0 ? '#27ae60' : '#e74c3c'}">(${sentiment})</span></h2>
        <p style="font-size: 16px; margin: 10px 0;">${report.summary}</p>
        <ul style="padding-left: 20px;">
          ${takeaways.map((t: string) => `<li style="margin-bottom: 5px;">${t}</li>`).join('')}
        </ul>
      </div>
    `;
  }

  emailHtml += `
      <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
      <p style="font-size: 12px; color: #999; text-align: center;">Generated by Oaktree Agent via Cloudflare Workers AI.</p>
    </div>
  `;

  // 3. Send Email using Cloudflare Email Binding
  // Note: This requires the [send_email] binding in wrangler.toml and a verified destination.
  try {
    const { createMimeMessage } = await import('mimetext');
    const msg = createMimeMessage();
    msg.setSender({ name: 'Oaktree Agent', addr: 'agent@oaktree.internal' });
    msg.setRecipient(env.EMAIL.destination_address);
    msg.setSubject(`Daily Market Intelligence - ${new Date().toLocaleDateString()}`);
    msg.addMessage({
      contentType: 'text/html',
      data: emailHtml
    });

    // Cloudflare specific sending logic
    await env.EMAIL.send(msg.asRaw());
    console.log("Daily report email sent successfully.");
  } catch (error) {
    console.error("Failed to send email report:", error);
    // Fallback log of HTML if email fails so user can at least see it in logs
    console.log("Email content (HTML):", emailHtml);
  }
}
